# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: .docker/vue/Dockerfile
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "cd client && yarn serve"
