version: 2.1
jobs:
  build:
    docker:
      - image: rogteam/laravel-workspace
    steps:
      - checkout
      # run test
      - run : cd client && yarn && yarn lint --no-fix
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[info][title] build $CIRCLE_BUILD_NUM | STATUS : Fail [/title]- Repository name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            - Author: $CIRCLE_USERNAME
            - Branch: $CIRCLE_BRANCH
            - Commit/pull request link: https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1
            - Build link: https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM
                [/info]
                " \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM/messages"
            fi
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[toall][info][title] build $CIRCLE_BUILD_NUM | STATUS : Success [/title]- Repository name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            - Author: $CIRCLE_USERNAME
            - Branch: $CIRCLE_BRANCH
            - Commit/pull request link: https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1
            - Build link: https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM
                [/info]
                " \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM/messages"
            fi
workflows:
  eslint:
    jobs:
      - build 