name: Pull_Comment
on:
  pull_request_review:
    types: [submitted]

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [[ true ]];  then
            curl -X POST -H "X-ChatWorkToken: b29a700e2d44bef2f40ae4a4c182d1ea" -d \
              "body=
              [info][title] New Request Submitted [/title]- New submitted URL: ${{ github.event.review.html_url }}
          - Author: ${{ github.event.review.user.login }} ( ${{ github.event.review.user.html_url }} )
          - Submitted at: ${{ github.event.review.submitted_at }}
          - Type: ${{ github.event.review.state }}[/info]
              " \
              "https://api.chatwork.com/v2/rooms/184594670/messages"
          fi
